motor_0:
  Bridge: 15.0
  CPR: 400
  Enable: 0
  Encoder: 1
  Ratio: 18.33
  Rotation: 1
  emergency: { Bridge_off: 2.0, Slope_time: 1.0, Timeout: 100}
  pid: { Frequency: 1, Kp: 0.6, Ki: 0.15, Kd: 0.2}
motor_1:
  Bridge: 15.0
  CPR: 400
  Enable: 0
  Encoder: 1
  Ratio: 18.33
  Rotation: -1
  emergency: { Bridge_off: 2.0, Slope_time: 1.0, Timeout: 100}
  pid: { Frequency: 1, Kp: 0.6, Ki: 0.15, Kd: 0.2}
